name = "verkup-save-api"
main = "worker.js"
compatibility_date = "2026-06-02"
workers_dev = true

[vars]
GITHUB_OWNER = "senyak1987-prog"
GITHUB_REPO = "verkup"
GITHUB_BRANCH = "main"
BITRIX_LAUNCH_STAGE_ID = "4"
BITRIX_PRODUCTION_STAGE_ID = "10"
ALLOWED_ORIGIN = "https://senyak1987-prog.github.io"
