name = "verkup-save-api"
main = "worker.js"
compatibility_date = "2026-06-02"
workers_dev = true

[vars]
GITHUB_OWNER = "senyak1987-prog"
GITHUB_REPO = "verkup"
GITHUB_BRANCH = "main"
BITRIX_TZ_STAGE_ID = "DETAILS"
BITRIX_TZ_STAGE_NAME = "Подготовка ТЗ"
BITRIX_TZ_APPROVAL_STAGE_ID = "13"
BITRIX_TZ_APPROVAL_STAGE_NAME = "Согласование ТЗ"
BITRIX_LAUNCH_STAGE_ID = "4"
BITRIX_LAUNCH_STAGE_NAME = "Запустить в производство"
BITRIX_PRODUCTION_STAGE_ID = "10"
BITRIX_PRODUCTION_STAGE_NAME = "В производстве"
BITRIX_DEFECT_STAGE_ID = "9"
BITRIX_DEFECT_STAGE_NAME = "КОСЯК в заказе"
BITRIX_DOMAIN = "verkup.bitrix24.ru"
BITRIX_FIELD_CLASSIFICATION = "UF_CRM_6512B7A78D965"
BITRIX_FIELD_INSTALL_AMOUNT = "UF_CRM_1547662428256"
BITRIX_TECH_SPEC_FILE_FIELD = "UF_CRM_1780210628536"
ALLOWED_ORIGIN = "https://senyak1987-prog.github.io,https://verkup-test.pages.dev,https://*.verkup-test.pages.dev"
